### ISSUE TITLE
Implement the facial recognition application code on Buildroot (Raspberry Pi 4)

### ISSUE THREAD

**Issue by tanmay-mk** [cu-ecen-aeld/final-project-Amey2904dash#8]
Assignee: Tanmay Mahendra Kothale

DoD: Implement the facial recognition source code (developed on userspace) on Buildroot using Raspberry Pi 4 board. 

Task:
- [x]  Add a new package to the existing image of Server buildroot (RPi 4)
- [x] Build the entire image again with newly added external package
- [x] Run the application code 
- [x] Verify the output

Blockers:
- [Errors in building](https://github.com/cu-ecen-aeld/final-project-Amey2904dash/issues/8#issuecomment-1101087777)
Resolved [Link](https://github.com/cu-ecen-aeld/final-project-Amey2904dash/issues/8#issuecomment-1101380388)

**Comment by tanmay-mk** [comment]
Firstly, when we tried to add python packages to support facial recognition libraries and the python source code, we found out that the buildroot toolchain required to support numpy and facial recognition libraries is glibc. Till now, we were working with uClibc. We changed the toolchain to glibc, cleaned the image and built again. 
![image](https://user-images.githubusercontent.com/89433097/163752638-2219c1d4-37a9-4ab4-a80b-413818914efe.png)

**Comment by tanmay-mk** [comment]
According to @dwalkes 's suggestion, we tried executing @saloni1307 's application code and tried to replicate the results on our system. However, while trying to do that, we faced the following issues. 

1. One of the package that was installed on the buildroot was giving an error which we didn't understand. We verified that the package was not defined repeatedly in the working directory. However, this error was still occurring. 
![python-packaging](https://user-images.githubusercontent.com/89433097/163753299-e45a9fe8-40c2-43fe-a56b-921707f5e68f.png)
**Fix** : We removed the package altogether from the buildroot external packages. 


2. Legacy packages were detected which were blocking the build. 
![legacy terminal output](https://user-images.githubusercontent.com/89433097/163753650-9035158a-f06b-471f-aa0c-50f71308e007.png)
![Legacy detected](https://user-images.githubusercontent.com/89433097/163752956-741b39f1-479a-42a9-b2e1-f81158092046.png)
![Legacy package](https://user-images.githubusercontent.com/89433097/163752970-28d9e2fd-eab5-43cb-bf62-0e98c8d25668.png)
We removed this legacy packages from the menuconfig and ran the re-built the image. 
**Update:** We found out that this package was counted as a legacy package because the toolchain selected was uclibc and not glibc. This was resolved when we re-built the image after cleaning. 

3. Python dependencies were found.  
![Dependencies issue](https://user-images.githubusercontent.com/89433097/163753680-2aa01705-8995-46e8-a259-0f38c208eae8.png)
Again, this was because the toolchain was set as uclibc and not glibc. All python packages require glibc as their toolchain. Even this issue was resolved.

**Comment by tanmay-mk** [comment]
However, we couldn't entirely replicate their results because of following reasons: 
1. Hardware availability: Their project implemented server on Raspberry Pi and client on BeagleBone Black. After watching their demo videos, we found out that facial recognition application was actually being seen on BeagleBone. 
2. Python package dependency: Their project had several other python packages and the were interdependent. Those packages were irrelevant to our project.

**Comment by tanmay-mk** [comment]
Taking insights from their project, we tried re-building our buildroot image with glibc toolchain. We cleaned the existing image and tried building a new one.

**Comment by tanmay-mk** [comment]
After selecting glibc as the toolchain, we observed that the rpi-wifi-firmware package, which is essential for SSH functionality of buildroot disappears. glibc considers rpi-wifi-firmware package as a legacy package. 
![image](https://user-images.githubusercontent.com/89433097/163754644-668cd9f0-2909-4207-8767-74b2f002fcd7.png)
This is not desirable. However, we found out that there is a substitute package for this. We are implementing this as of now, but there is no documentation that corroborates functionality of this substitute package. 
![image](https://user-images.githubusercontent.com/89433097/163754776-dc5c1b0d-f9af-4e18-8350-ba7e9fb58d59.png)

**Comment by tanmay-mk** [comment]
According to [this ](https://github.com/cu-ecen-aeld/final-project-saloni1307/issues/2#issuecomment-966738578) suggestion, we tried installing following packages. We did not need eye-game package, so we didn't install it. However, we are facing issues in other packages.
![image](https://user-images.githubusercontent.com/89433097/163755101-255055db-339f-46e6-a3d1-25c7f1ea8d64.png)
This could be one of the reason our build is failing at this moment. 

**Update:** Instead of cv2, we installed cv, but not sure whether it meets the requirements.

**Comment by tanmay-mk** [comment]
At this point, we are trying to resolve these errors after running build.sh. 
![make error](https://user-images.githubusercontent.com/89433097/163755253-d98ea491-d433-4351-930a-4ae4195879b3.png)

**Comment by tanmay-mk** [comment]
Latest buildroot recipe pushed:
Commit: 3805a602cc55768ae9c38b7cefc3a51df7a6a0d8
Link: https://github.com/cu-ecen-aeld/final-project-varun2506/commit/3805a602cc55768ae9c38b7cefc3a51df7a6a0d8

**Note:** There was no source code written in this sprint. My only goal was to implement the facial recognition package on buildroot. Hence, only recipe for server board was changed. Since the server board's buildroot implementation is on [Varun's repository](https://github.com/cu-ecen-aeld/final-project-varun2506), the commit number provided is of his repo.

**Comment by tanmay-mk** [comment]
Successfully built the image after resolving the errors. Apparently starting fresh helped. We started from scratch, followed the steps and built the image. We took help from [this ](https://github.com/cu-ecen-aeld/final-project-saloni1307/issues/2) and [this ](https://github.com/cu-ecen-aeld/final-project-saloni1307/issues/3)issue. 

Could not push the latest recipe code to github because of [this ](https://github.com/cu-ecen-aeld/final-project-Amey2904dash/issues/8#issuecomment-1101381781) reason. We lost the GUI and therefore it was impossible to get personal access token stored on the VM. We'll push the recipe as soon as we resolve the issue.

**Comment by tanmay-mk** [comment]
Reference: https://github.com/cu-ecen-aeld/final-project-saloni1307/issues/3#issuecomment-968334781

This particular step is necessary for the build, however it messes up entire virtual machine disk file. It is explicitly mentioned that the host configuration of virtual machine will change and it will only boot in console mode and not GUI. 

One way around this is to take a back-up of the image and re-build it on virtual machine every time we lose GUI. We are looking for a way to circumvent this. [Link](https://github.com/cu-ecen-aeld/final-project-saloni1307/issues/3#:~:text=These%20commands%20change%20the%20image%20configuration%20of%20host%20(in%20this%20case%20ubuntu)%20in%20virtual%20machine.%20It%20then%20only%20boots%20in%20console%20mode.%20Do%20not%20repeat%20these%20steps.)

**Comment by tanmay-mk** [comment]
We tried running our application code on buildroot, currently facing following error. 
![image](https://user-images.githubusercontent.com/89433097/163811906-403117ea-7db0-4883-ab85-ae035bab8bc9.png)


We suspect that the error is not in the packages installed but in the source code itself. We will now try to change the application code and take some reference to speed through the process.

**Comment by tanmay-mk** [comment]
https://github.com/cu-ecen-aeld/final-project-Amey2904dash/issues/8#issuecomment-1101381781

This problem was solved. Turns out there is a change in the /buildroot/output/build/dlib-v19.17/dlib/external/pybind11/tools/FindPythonLibsNew.cmake file. 
Referred from: https://github.com/cu-ecen-aeld/final-project-saloni1307/issues/3#issuecomment-969698149

Make changes according to this fix: https://github.com/cu-ecen-aeld/buildroot/blob/package-dlib/package/dlib/0001-pybind11-cmake-ignore-the-check-between-host-python-.patch

No need to shift to 32 bit python, which kills GUI.

**Comment by Amey2904dash** [comment]
![image](https://user-images.githubusercontent.com/89843479/163825011-7d2b2a8d-f8fa-4901-a25f-34f94c2cef16.png)

**Comment by tanmay-mk** [comment]
Facing this error when executing the application code. Initially pip was not installed in buildroot image. After installing pip, we are facing this error. 

![image](https://user-images.githubusercontent.com/89843479/163825011-7d2b2a8d-f8fa-4901-a25f-34f94c2cef16.png)

**Comment by tanmay-mk** [comment]
[This](https://github.com/cu-ecen-aeld/final-project-Amey2904dash/issues/8#issuecomment-1101464851) error is generated because this line 65 in buildroot-assignments-base/buildroot/output/host/usr/lib/python3.8/plistlib.py file.
![image](https://user-images.githubusercontent.com/89433097/163896990-9103fcb5-fb67-4c84-bf4a-82fe9a32e90c.png)

**Comment by tanmay-mk** [comment]
Trying to import [xml.parsers.expat](https://pypi.org/project/pycopy-xml.parsers.expat/#files) package but facing the following error during build. 
![image](https://user-images.githubusercontent.com/89433097/163897160-fbc6a973-c443-4fe5-bb27-5be4dfcd4391.png)

**Comment by tanmay-mk** [comment]
Tried installing xml.parsers.expat package on Linux but facing this issue. 
![image](https://user-images.githubusercontent.com/89433097/163897200-dc947366-b07d-4013-829c-fee7630ad6f8.png)

**Comment by tanmay-mk** [comment]
@dwalkes helped us recognize what the problem was. Apparently, all the packages were installed but even then buildroot was not showing all the packages. Cleaning and rebuilding python3 helped. We followed the following steps:

**(Inside your assignment repository)**
`cd buildroot`
`make python3-dirclean`
`make python3-rebuild`

After performing these steps, all python3 packages will be removed completely and rebuilt by buildroot.

**Comment by tanmay-mk** [comment]
After doing [these](https://github.com/cu-ecen-aeld/final-project-Amey2904dash/issues/8#issuecomment-1106215124) steps, we saved the buildroot configuration using [save_config.sh](https://github.com/cu-ecen-aeld/final-project-varun2506/blob/main/save_config.sh), and built a new buildroot image using [build.sh](https://github.com/cu-ecen-aeld/final-project-varun2506/blob/main/build.sh).

**Comment by tanmay-mk** [comment]
We added our facial recognition code on the rootfs_overlay. The link to the code can be found [here](https://github.com/cu-ecen-aeld/final-project-tanmay-mk/tree/main/face-rec)

**Comment by tanmay-mk** [comment]
Successfully implemented the facial recognition code on Buildroot. 
![face rec update](https://user-images.githubusercontent.com/89433097/164675996-613a0678-d685-4a79-a8bd-8ce30094f25e.png)

**Comment by tanmay-mk** [comment]
Buildroot Configuration updated in Server ([Varun's](https://github.com/cu-ecen-aeld/final-project-varun2506)) repository. 
Commit Number: 14b27147f4daa3c03285eb019ab5228a6fe87727
Link: https://github.com/cu-ecen-aeld/final-project-varun2506/commit/14b27147f4daa3c03285eb019ab5228a6fe87727

Code updated. 
Commit number: 0ab47bb4fae55f4d645e863022efc77fb0ff53a7
Commit Link: https://github.com/cu-ecen-aeld/final-project-tanmay-mk/commit/0ab47bb4fae55f4d645e863022efc77fb0ff53a7
Code Link: https://github.com/cu-ecen-aeld/final-project-tanmay-mk/tree/main/face-rec
